/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.Random;
import model.Observer;
import model.Subject;
import presenter.PainelClimaAtualPresenter;

/**
 *
 * @author Fernando Paiva
 */
public class PainelClimaAtualView extends javax.swing.JInternalFrame implements Subject, Observer {

    /**
     * Creates new form PainelClimaView
     */
    
    public ArrayList<Observer> observers;
    
    private Double temp; 
    private Double umid;
    private Double press; 
    
    
    public PainelClimaAtualView() {
        initComponents();
        
        temp = 0.0; 
        umid = 0.0;
        press = 0.0; 
        
        //registerObserver(new PainelClimaAtualPresenter());
           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        txtTempAtual = new javax.swing.JTextField();
        txtUmidAtual = new javax.swing.JTextField();
        txtPressAtual = new javax.swing.JTextField();

        setTitle("Clima atual");

        jLabel1.setText("Temperatura");
        jLabel1.setName("lbTempAtual"); // NOI18N

        jLabel2.setText("Umidade");
        jLabel2.setName("lbUmidAtual"); // NOI18N

        jLabel3.setText("Pressão");
        jLabel3.setName("lbPressAtual"); // NOI18N

        btnAtualizar.setText("Atualizar");
        btnAtualizar.setName("btnAtualizar"); // NOI18N
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        txtTempAtual.setName("txtTempAtual"); // NOI18N

        txtUmidAtual.setName("txtUmidAtual"); // NOI18N

        txtPressAtual.setName("txtPressAtual"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAtualizar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPressAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(txtUmidAtual, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTempAtual, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTempAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUmidAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPressAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnAtualizar)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        
        Random random = new Random(); 
        temp = random.nextDouble() * 40;
        umid = random.nextDouble() * 100;
        press = ((random.nextDouble() * 40) + 1);
        
        txtTempAtual.setText(String.valueOf(random.nextDouble() * 40));
        txtUmidAtual.setText(String.valueOf(random.nextDouble() * 100));
        txtPressAtual.setText(String.valueOf((random.nextDouble()+ 0.5)));
        
        //registerObserver(new PainelClimaAtualPresenter());
        //registerObserver(new PainelClimaAnteriorView());
        
        //notifyObservers();
     
    }//GEN-LAST:event_btnAtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtPressAtual;
    private javax.swing.JTextField txtTempAtual;
    private javax.swing.JTextField txtUmidAtual;
    // End of variables declaration//GEN-END:variables

    @Override
    public void registerObserver(Observer o) {
        observers.add(o);
        
    }

    @Override
    public void removeObserver(Observer o) {
        //presenters.remove(o);
    }

    @Override
    public void notifyObservers() {
                
        for (int i = 0; i < observers.size(); i++) {
            Observer ob = observers.get(i);
            ob.update(temp, umid, press);
        }
        
    }

    @Override
    public void update(Double temperatura, Double umidade, Double pressao) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
