/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.PainelEstatistica;

/**
 *
 * @author Fernando Paiva
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    
    public PainelClimaAtualView painelClimaAtual;
    public PainelClimaAnteriorView painelClimaAnterior;
    public PainelEstatisticaView painelEstatistica;
    
    //public ArrayList<Observer> observers;
    
    public PrincipalView() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JDesktopPane();
        mbPrincipal = new javax.swing.JMenuBar();
        mnPrincipal = new javax.swing.JMenu();
        miClimaAtual = new javax.swing.JMenuItem();
        miClimaAnterior = new javax.swing.JMenuItem();
        miEstatistica = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clima Tempo");
        setName("climaTempoFrame"); // NOI18N

        painelPrincipal.setName("painelPrincipal"); // NOI18N

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        mbPrincipal.setName("mbPrincipal"); // NOI18N

        mnPrincipal.setText("Janela");
        mnPrincipal.setName("mnPrincipal"); // NOI18N

        miClimaAtual.setText("Clima atual");
        miClimaAtual.setName("miClimaAtual"); // NOI18N
        miClimaAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClimaAtualActionPerformed(evt);
            }
        });
        mnPrincipal.add(miClimaAtual);

        miClimaAnterior.setText("Clima anterior");
        miClimaAnterior.setName("miClimaAnterior"); // NOI18N
        miClimaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClimaAnteriorActionPerformed(evt);
            }
        });
        mnPrincipal.add(miClimaAnterior);

        miEstatistica.setText("Estatística");
        miEstatistica.setName("miEstatistica"); // NOI18N
        miEstatistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEstatisticaActionPerformed(evt);
            }
        });
        mnPrincipal.add(miEstatistica);

        mbPrincipal.add(mnPrincipal);

        setJMenuBar(mbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miClimaAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClimaAtualActionPerformed
        // TODO add your handling code here:
        painelClimaAtual = new PainelClimaAtualView();
        //registerObserver(painelClimaAtual);
        
        painelPrincipal.add(painelClimaAtual);
        painelClimaAtual.setVisible(true);
        painelClimaAtual.setLocation(0, 0);
    }//GEN-LAST:event_miClimaAtualActionPerformed

    private void miClimaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClimaAnteriorActionPerformed
        // TODO add your handling code here:
        painelClimaAnterior = new PainelClimaAnteriorView();
        //registerObserver(new PainelClimaAnteriorPresenter());
        
        painelPrincipal.add(painelClimaAnterior);
        painelClimaAnterior.setVisible(true);
        painelClimaAnterior.setLocation(220, 0);
    }//GEN-LAST:event_miClimaAnteriorActionPerformed

    private void miEstatisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEstatisticaActionPerformed
        // TODO add your handling code here:
        painelEstatistica = new PainelEstatisticaView();
        
        painelPrincipal.add(painelEstatistica);
        painelEstatistica.setVisible(true);
        painelEstatistica.setLocation(440, 0);
    }//GEN-LAST:event_miEstatisticaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mbPrincipal;
    private javax.swing.JMenuItem miClimaAnterior;
    private javax.swing.JMenuItem miClimaAtual;
    private javax.swing.JMenuItem miEstatistica;
    private javax.swing.JMenu mnPrincipal;
    private javax.swing.JDesktopPane painelPrincipal;
    // End of variables declaration//GEN-END:variables

    
}
